### ISSUE TITLE
Minecraft stat table changes

### ISSUE THREAD

**Issue by nierw** [Maximvdw/MVdWPlaceholderAPI#22]
Changes in MC seem to be causing this error with any time stat-related placeholders:

```
22/02/2020 11:48:03 [SEVERE] java.lang.NoSuchFieldError: PLAY_ONE_TICK
        at be.maximvdw.placeholdercore.placeholders.StatisticPlaceholderPack$42.getResult(StatisticPlaceholderPack.java:456)
        at be.maximvdw.placeholdercore.placeholders.StatisticPlaceholderPack$42.getResult(StatisticPlaceholderPack.java:452)
        at be.maximvdw.conditionpermscore.b.a(Unknown Source)
        at be.maximvdw.conditionpermscore.b.a(Unknown Source)
        at be.maximvdw.conditionperms.a.b.a(DebugCommand.java:175)
        at be.maximvdw.conditionperms.a.b.a(DebugCommand.java:33)
        at be.maximvdw.conditionperms.a.b$1.run(DebugCommand.java:132)
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

A few examples:
* `{stat_days_played_remaining}`
* `{stat_minutes_played_remaining}`

**Comment by Chew** [comment]
Have this with {stat_time_played}, PlaceholderAPI/PlaceholderAPI has this fixed, kinda sad it isn't here.
